services:
  frontend:
    container_name: easy-sudoku-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8006
    depends_on:
      - api_nginx
    stdin_open: true
    tty: true

  api:
    container_name: easy-sudoku-api-dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/var/www
      - api_storage_easy_sudoku:/var/www/storage
    expose:
      - "9000"
    depends_on:
      - db
    env_file:
      - ./api/.env

  api_nginx:
    container_name: easy-sudoku-api-nginx-dev
    image: nginx:1.29.1-alpine
    restart: unless-stopped
    ports:
      - "8006:80"
    volumes:
      - ./nginx.api.conf:/etc/nginx/conf.d/default.conf
      - ./api/public:/var/www/public
    depends_on:
      - api

  db:
    image: postgres:17-alpine
    container_name: easy-sudoku-db-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_easy_sudoku:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres_data_easy_sudoku:
  api_storage_easy_sudoku:

