services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    image: ghcr.io/dgox16/easy-sudoku-frontend:latest
    container_name: easy-sudoku-frontend-container
    restart: unless-stopped
    ports:
      - "8005:80"

  api:
    image: ghcr.io/dgox16/easy-sudoku-api:latest
    container_name: easy-sudoku-api-container
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - api_storage_easy_sudoku:/var/www/storage
      - api_cache_easy_sudoku:/var/www/bootstrap/cache
    depends_on:
      - db
    env_file:
      - ./api/.env.produccion

  api_nginx:
    image: nginx:1.29.1-alpine
    container_name: easy-sudoku-api-nginx
    restart: unless-stopped
    ports:
      - "8006:80"
    volumes:
      - ./nginx.api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: postgres:17-alpine
    container_name: easy-sudoku-db-container
    restart: unless-stopped
    volumes:
      - postgres_data_easy_sudoku:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres_data_easy_sudoku:
  api_storage_easy_sudoku:
  api_cache_easy_sudoku:
