GET http://localhost:8000/sudoku/new-game?difficult=hard
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8000/sudoku/new-movement
Accept: application/json
Content-Type: application/json

{
    "game_id": 3,
    "timer": 100,
    "current_grid": [
        [2, 0, 3, 0, 0, 7, 0, 0, 0],
        [0, 5, 0, 2, 0, 8, 0, 0, 0],
        [0, 0, 0, 0, 9, 0, 0, 0, 7],
        [0, 7, 9, 0, 3, 0, 0, 1, 0],
        [0, 0, 1, 9, 0, 0, 0, 0, 0],
        [6, 0, 0, 7, 1, 0, 3, 5, 0],
        [7, 8, 2, 0, 0, 3, 0, 9, 1],
        [0, 4, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 8, 0, 0, 4, 2]
    ]
}
